<%@ page language="java" import="java.util.*,java.sql.*,org.apache.log4j.*" pageEncoding="ISO-8859-1"%>

<jsp:useBean id='user' class='user.UserBean'  scope='session'/>
<jsp:useBean id='connect' class='ConnectBean.ConnectBean'  scope='session'/>
<jsp:useBean id='create' class='create_main.Create' scope='session'/>

<jsp:include page="/jsp/page/check_credentials.jsp" />
<jsp:include page="/jsp/page/check_input.jsp" />
<jsp:include page="/jsp/page/page_head.jsp" />

<td colspan="2" width="81%" align="left" valign="top" background="./images/possbk.jpg"><table width="1200" border="0" cellspacing="0" cellpadding="10"> 
      <tr> 
        <td width="15" align="left" valign="top">&nbsp;</td> 
        <td align="left" valign="top"><!-- #BeginEditable "MainText" --> 

<jsp:include page="/jsp/page/page_nav.jsp" />


<%
ServletContext context = getServletContext();
String path = request.getContextPath();
String baseUrl = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
Connection conn = connect.getConnection();
Connection paramConn = connect.getParamConnection();
Connection ccConn = connect.getCcConnection();

String username = user.getUsername();
create.setUsername(username);

String userCenter = user.getCenter(); 
String dbn = request.getParameter("dbn"); 
String dbid = request.getParameter("dbid"); 
String lineColour = create.getLineColour(dbn);

//Retrieve data parameter information
String[] tablenames = new String[1];
tablenames[0] = "Identification";
Vector<Vector> parameters = create.getParameters(tablenames,request,paramConn);

//Retrieve associated menu information
Vector<Vector> menus = create.getMenus(parameters,paramConn);
menus = create.getDynamicMenus(parameters, menus, userCenter, ccConn, conn,"","",dbn);

//Logging configuration
String log4jConfigFile = context.getInitParameter("log4j_property_file");
Logger logger = Logger.getLogger("rootLogger");
logger.setLevel(Level.DEBUG);
PropertyConfigurator.configure(log4jConfigFile);
logger.debug("('" + username + "') - create_view.jsp");

String javascriptValidationArray = create.getJavascriptValidationArray(parameters,baseUrl);
%>
<%=javascriptValidationArray%>


<h1>Create <%=dbn%> Record</h1>

<p><div id="create"></div></p>

<h2>Identification</h2>

<p><div id="minimuminputflag">The following data points are the minimum criteria required for creating a patient record.</div></p>

<form action="./jsp/create/create_view_2.jsp?dbid=<%=dbid%>&dbn=<%=dbn%>" method="POST" onsubmit="return validateForm(this,'create','<%=dbn%>','','<%=baseUrl%>');">
    
<table border="1px" width="75%" cellpadding="10">

    <tr <%=lineColour%>>
        <td width="50%">ENSAT ID Number:</td><td><strong>[AutoGenerated]</strong></td>
    </tr>

    <%
    String parameterHtml = create.getParameterHtml(parameters, menus, lineColour, dbn, conn, baseUrl);
    %>
    <%= parameterHtml %>

</table>
<input type="submit" name="create_record" value="Confirm Details"/>
</form>

<jsp:include page="/jsp/page/page_foot.jsp" />
</td> 
      </tr> 
    </table> 
    </td> 
    
</tr>
</table>


